sonar.projectKey=sit753-devops-app-key
sonar.projectName=sit753-devops-app
sonar.sources=.
sonar.python.version=3.9
sonar.host.url=http://localhost:9000
sonar.token=sqp_8d22f05acdc84c300fa7f86430a280baba3e4419
